### PR TITLE
XSS Sanitisation Patch

### PR DESCRIPTION
**Pull request by ProDigySML**
Added in HTML Encoding for all echo statements. This should take care of any XSS issues that are within the software.

### CODE REVIEW

**Comment by JustinStolle** [comment]
Not sure why, but this is what I see when using your copy of the file, @ProDigySML .
problem

**Comment by ProDigySML** [comment]
My bad. Probably over sanitised sections. Looking into fixing it.

**Comment by ProDigySML** [comment]
@JustinStolle Just added in a patch for that. Should be patched, but still has a bit of a problem if someone uses things like chevrons (<>)

**Comment by ProDigySML** [comment]
@osalabs Thanks for that! I made the change to use hs now. Also fixed up the spaces issue.

**Pull request closed without merging**
