### PR TITLE
Encode all queries in base64 before sending it to server 

### PR DESCRIPTION
**Pull request by dinoel**
Encode all queries in base64 before sending it to server to prevent blocking by applications firewalls which checks for sql statements in request.  Using window.btoa() which is available from IE10 .

### CODE REVIEW

**Comment by osalabs** [comment]
dinoel, thank you for your input, reviewing. 
Could you tell me some example which application firewalls blocks requests? Just want to investigate scope of the issue.

**Comment by dinoel** [comment]
osalabs, for example cloudfare web application firewall (https://www.cloudflare.com/waf/) , if enabled, block all requests which looks like sql queries.
See here, for example : http://securityidiots.com/Web-Pentest/WAF-Bypass/waf-bypass-guide-part-1.html#waf

I tested my solution on my customer's site with cloudfare WAF enabled, and it works fine.

**Comment by wiperawa** [comment]
i have the same problem alot of times on servers, when you post SQL query by POST dont encoded, you get error. Too annoying when you try to debug app and cant get to database.

**Comment by osalabs** [comment]
Made some changes, cleanup, testing. Looks like everything works. 
Released in 1.9.160630, thanks for contributing.

**Pull request merged**
